version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      production-patch-minor:
        dependency-type: production
        update-types:
          - patch
          - minor
      dev-tooling:
        dependency-type: development
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci(deps)
